-- @description ReaProfessor
-- @version 0.3.3
-- @author JewishBidoof
-- @metapackage
-- @provides
--   [main] ../scripts/ReaProfessor/ReaProfessor.lua > ReaProfessor/ReaProfessor.lua
--   [main] ../scripts/ReaProfessor/install_extensions_menu.lua > ReaProfessor/install_extensions_menu.lua
--   [main] ../scripts/ReaProfessor/cue_list.lua > ReaProfessor/cue_list.lua
--   [main] ../scripts/ReaProfessor/snapshots.lua > ReaProfessor/snapshots.lua
--   [main] ../scripts/ReaProfessor/chain_rack.lua > ReaProfessor/chain_rack.lua
--   [main] ../scripts/ReaProfessor/create_channels.lua > ReaProfessor/create_channels.lua
--   [main] ../scripts/ReaProfessor/live_mode.lua > ReaProfessor/live_mode.lua
--   [main] ../scripts/ReaProfessor/control_panel.lua > ReaProfessor/control_panel.lua
--   [main] ../scripts/ReaProfessor/control_service.lua > ReaProfessor/control_service.lua
--   [main] ../scripts/ReaProfessor/mapping.lua > ReaProfessor/mapping.lua
--   [nomain] ../scripts/ReaProfessor/lib/commands.lua > ReaProfessor/lib/commands.lua
--   [nomain] ../scripts/ReaProfessor/lib/config.lua > ReaProfessor/lib/config.lua
--   [nomain] ../scripts/ReaProfessor/lib/data.lua > ReaProfessor/lib/data.lua
--   [nomain] ../scripts/ReaProfessor/lib/menu.lua > ReaProfessor/lib/menu.lua
--   [nomain] ../scripts/ReaProfessor/lib/midi.lua > ReaProfessor/lib/midi.lua
--   [nomain] ../scripts/ReaProfessor/lib/osc.lua > ReaProfessor/lib/osc.lua
--   [nomain] ../scripts/ReaProfessor/lib/path.lua > ReaProfessor/lib/path.lua
--   [nomain] ../scripts/ReaProfessor/lib/routing.lua > ReaProfessor/lib/routing.lua
--   [nomain] ../scripts/ReaProfessor/lib/ui.lua > ReaProfessor/lib/ui.lua
--   [data] ../resources/osc/ReaProfessor.ReaperOSC > ReaProfessor.ReaperOSC
-- @changelog
--   + Prototype mode: all show/project commands gated until finalized
--   + Extensions → ReaProfessor menu installer
--   + Fix gfx crash when opening panels from hub
-- @about
--   Live-oriented REAPER toolkit inspired by LiveProfessor 2.
--   Run Actions → ReaProfessor, then "Install Extensions menu".
--   Restart REAPER once to see Extensions → ReaProfessor.
